"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, CalendarDays, Gift, Infinity, PackageCheck, Save, ShieldCheck } from "lucide-react";

type Resgate = { id: string; recompensa: string; estoqueDepois: number | null; createdAt: Date | string; cartao: { cliente: { nome: string } } };
type Props = { inicial: { recompensa: string; recompensaEstoque: number | null; recompensaValidaAte: Date | string | null; recompensaRegras: string | null }; resgates: Resgate[] };
function dataInput(valor: Date | string | null) { return valor ? new Date(valor).toISOString().slice(0, 10) : ""; }

export default function RecompensasManager({ inicial, resgates }: Props) {
  const router = useRouter();
  const [recompensa, setRecompensa] = useState(inicial.recompensa);
  const [controlaEstoque, setControlaEstoque] = useState(inicial.recompensaEstoque !== null);
  const [estoque, setEstoque] = useState(String(inicial.recompensaEstoque ?? 0));
  const [validaAte, setValidaAte] = useState(dataInput(inicial.recompensaValidaAte));
  const [regras, setRegras] = useState(inicial.recompensaRegras ?? "");
  const [salvando, setSalvando] = useState(false);
  const [mensagem, setMensagem] = useState("");

  async function salvar() {
    setSalvando(true); setMensagem("");
    const res = await fetch("/api/recompensas", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recompensa, controlaEstoque, estoque: Number(estoque), validaAte, regras }) });
    const data = await res.json(); setSalvando(false);
    if (!res.ok) { setMensagem(data.error ?? "Não foi possível salvar agora."); return; }
    setMensagem("Recompensa atualizada. As novas regras já valem para os próximos resgates."); router.refresh();
  }

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
    <section className="relative overflow-hidden rounded-[2rem] border border-amber-300/15 bg-zinc-900/70 p-5 shadow-2xl shadow-black/20 backdrop-blur-xl sm:p-7"><div className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-amber-400/[.09] blur-3xl" /><div className="relative"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-amber-300/25 bg-amber-300/[.1] text-amber-200"><Gift className="h-5 w-5" /></div><div><h2 className="text-xl font-black tracking-tight text-white">O prêmio que você entrega</h2><p className="mt-1 text-sm leading-6 text-zinc-400">O cartão continua simples para o cliente; aqui você controla a operação por trás dele.</p></div></div>
      <div className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[.14em] text-zinc-400">Recompensa</span><input value={recompensa} onChange={(e) => setRecompensa(e.target.value)} maxLength={140} placeholder="Ex.: 1 corte grátis" className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3.5 text-base font-bold text-white outline-none transition focus:border-amber-300/55 focus:ring-4 focus:ring-amber-300/10" /></label>
        <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black text-white">Controlar estoque</p><p className="mt-1 text-xs leading-5 text-zinc-500">Bloqueia resgate ao zerar.</p></div><button type="button" onClick={() => setControlaEstoque(!controlaEstoque)} aria-pressed={controlaEstoque} className={`relative h-7 w-12 rounded-full transition ${controlaEstoque ? "bg-amber-300" : "bg-white/15"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-zinc-950 shadow transition ${controlaEstoque ? "left-6" : "left-1"}`} /></button></div>{controlaEstoque ? <label className="mt-4 block"><span className="mb-1.5 block text-xs font-bold text-zinc-400">Quantidade disponível</span><input type="number" min="0" step="1" value={estoque} onChange={(e) => setEstoque(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm font-bold text-white outline-none focus:border-amber-300/55" /></label> : <div className="mt-4 flex items-center gap-2 text-xs font-bold text-zinc-500"><Infinity className="h-4 w-4" /> Sem limite de quantidade</div>}</div>
          <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center gap-2 text-white"><CalendarDays className="h-4 w-4 text-amber-200" /><p className="text-sm font-black">Validade</p></div><p className="mt-1 text-xs leading-5 text-zinc-500">Opcional. Depois da data, o resgate é bloqueado.</p><input type="date" value={validaAte} onChange={(e) => setValidaAte(e.target.value)} className="mt-4 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm font-bold text-white [color-scheme:dark] outline-none focus:border-amber-300/55" /></div></div>
        <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[.14em] text-zinc-400">Condição curta para o cliente <span className="font-medium normal-case tracking-normal text-zinc-600">(opcional)</span></span><textarea value={regras} onChange={(e) => setRegras(e.target.value)} rows={3} maxLength={420} placeholder="Ex.: Válido para consumo no local, de terça a quinta." className="w-full resize-none rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none transition focus:border-amber-300/55 focus:ring-4 focus:ring-amber-300/10" /></label>
        {mensagem && <p className={`rounded-xl px-3 py-2.5 text-sm ${mensagem.startsWith("Recompensa") ? "bg-emerald-400/10 text-emerald-200" : "bg-red-400/10 text-red-200"}`}>{mensagem}</p>}<button type="button" onClick={salvar} disabled={salvando} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-amber-300 px-5 py-3.5 text-sm font-black text-zinc-950 transition hover:bg-amber-200 disabled:opacity-60"><Save className="h-4 w-4" />{salvando ? "Salvando..." : "Salvar regras da recompensa"}</button></div></div></section>
    <aside className="space-y-4"><div className="rounded-[1.75rem] border border-emerald-300/15 bg-emerald-300/[.07] p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-200" /><div><p className="font-black text-white">Resgate seguro</p><p className="mt-1 text-xs leading-5 text-emerald-50/60">Só o atendente, com o cartão completo, consegue confirmar a entrega.</p></div></div></div><div className="rounded-[1.75rem] border border-white/10 bg-zinc-900/60 p-5"><div className="flex items-center gap-2"><Archive className="h-4 w-4 text-amber-200" /><h2 className="text-sm font-black uppercase tracking-[.14em] text-white">Últimos resgates</h2></div>{resgates.length === 0 ? <p className="mt-5 text-sm leading-6 text-zinc-500">Quando uma recompensa for entregue, ela ficará registrada aqui.</p> : <div className="mt-4 space-y-3">{resgates.map((resgate) => <div key={resgate.id} className="rounded-2xl border border-white/[.07] bg-white/[.035] p-3.5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-white">{resgate.cartao.cliente.nome}</p><p className="mt-1 text-xs text-zinc-400">{resgate.recompensa}</p></div><PackageCheck className="h-4 w-4 shrink-0 text-emerald-300" /></div><p className="mt-2 text-[11px] font-medium text-zinc-500">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(resgate.createdAt))}{resgate.estoqueDepois !== null ? ` · ${resgate.estoqueDepois} em estoque` : ""}</p></div>)}</div>}</div></aside></div>;
}
